version: '3.5'

services:
  transfer:
    build: .
    environment:
      CONFIG_PATH: /opt/demo-configs/filesystem-to-minio/config.json
      CONCURRENCY: 5
    volumes:
      - .:/opt
    networks:
      - net
  minio:
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    environment:
      MINIO_ACCESS_KEY: myaccess
      MINIO_SECRET_KEY: mysecret
    ports:
      - "9000:9000"
    command: ["server", "/data"]
    networks:
      - net

networks:
  net:
    